version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - mqtt-net
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-log:/var/log/mosquitto/
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    networks:
      - mqtt-net
    environment:
      - TZ=UTC
    depends_on:
      - mqtt-broker
    volumes:
      - ./node-red-data:/data

  influxdb:  # Add the InfluxDB service
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=ESP32
      - DOCKER_INFLUXDB_INIT_BUCKET=ESP32_Data
    volumes:
      - ./Influx:/var/lib/influxdb2
    ports:
      - "8086:8086"  # InfluxDB HTTP API port

networks:
  mqtt-net:
